name: Push DeepStream to Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Maximize Build Space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo docker image prune -a -f

      - name: Pull DeepStream Image
        run: docker pull nvcr.io/nvidia/deepstream:7.0-triton-multiarch

      - name: Save and Compress
        run: |
          # 边导出边压缩
          docker save nvcr.io/nvidia/deepstream:7.0-triton-multiarch | gzip > deepstream_7.0.tar.gz

      - name: Split File into 2GB Chunks
        # 将大文件切分成 2GB 一个的小块，后缀为 .aa, .ab, .ac...
        run: |
          split -b 2000M deepstream_7.0.tar.gz deepstream_7.0.tar.gz.part-

      - name: Create Release and Upload Chunks
        uses: softprops/action-gh-release@v1
        with:
          # 使用通配符上传所有切片文件
          files: deepstream_7.0.tar.gz.part-*
          tag_name: v7.0-${{ github.run_number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
